### ISSUE TITLE
Out of memory with too many data for exporter

### ISSUE THREAD

**Issue by holzheu** [BayCEER/bayeos-gateway#2]
gateway.log:
2014-06-18 15:54:14,077 [Thread-11] INFO  gateway.ExportJob  - Syncing 2 boards
2014-06-18 15:54:14,102 [Thread-11] INFO  gateway.ExportJob  - Syncing board: Stromzähler-Server
2014-06-18 15:54:14,145 [Thread-11] INFO  gateway.ExportJob  - Syncing board: Solar
2014-06-18 15:54:14,159 [Thread-11] INFO  gateway.ExportJob  - Exporting observations
....
....
2014-06-18 16:03:17,909 [TP-Processor5] ERROR errors.GrailsExceptionResolver  - OutOfMemoryError occurred when processing request: [POST] /gateway/frame/saveFlat
Java heap space. Stacktrace follows:
org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [saveFlat] of controller [gateway.FrameController]  caused exception: Runtime error executing action
	at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
	at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
	at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:776)
	at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:705)
	at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:898)
	at java.lang.Thread.run(Thread.java:744)
Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Runtime error executing action
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	... 6 more
Caused by: java.lang.OutOfMemoryError: Java heap space
2014-06-18 16:03:17,785 [Thread-11] INFO  gateway.ExportJob  - ExportJob finished

No rows are exported:

XMLServlet.log:
 2014-06-18 15:54:11,203 INFO  de.unibayreuth.bayceer.bayeos.xmlrpc.handler.LoginHandler.authenticate  - Authentication User:root from IP:127.0.0.1
 2014-06-18 16:03:17,778 INFO  de.unibayreuth.bayceer.bayeos.xmlrpc.handler.LogOffHandler.terminateSession  - Terminated session 735874284 for userid 100004.

**Comment by oarchner** [comment]
Cause of error unknown. Non-recurrent event.
