### ISSUE TITLE
Change DB-Type of message from varchar(255) to text

### ISSUE THREAD

**Issue by holzheu** [BayCEER/bayeos-gateway#21]
Message length in the database is limited to 255. Sending Messages from python-package could easily reach this limit leading to a 500-Error:

<pre>
2015-09-30 08:07:24,888 [TP-Processor12] ERROR errors.GrailsExceptionResolver  - PSQLException occurred when processing request: [POST] /gateway/frame/saveFlat
FEHLER: Wert zu lang für Typ character varying(255). Stacktrace follows:
org.postgresql.util.PSQLException: FEHLER: Wert zu lang für Typ character varying(255)
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:334)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at gateway.FrameService$FlatHandler.message(FrameService.groovy:105)
	at frame.parser.FrameParser.parse(FrameParser.java:60)
	at frame.parser.FrameParser.parse(FrameParser.java:43)
	at gateway.FrameService.parseFrames(FrameService.groovy:41)
	at gateway.FrameService.saveFlatFrames(FrameService.groovy:72)
	at gateway.FrameController.saveFlat(FrameController.groovy:25)
	at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
	at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
	at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:776)
	at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:705)
	at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:898)
	at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by oarchner** [comment]
Changeset 130 in 1.9.20
