### ISSUE TITLE
FrameParserError

### ISSUE THREAD

**Issue by holzheu** [BayCEER/bayeos-gateway#7]
Parser Exception führt zu Endlosschleife:

2014-11-13 08:09:25,346 [TP-Processor6] INFO  gateway.FrameController  - Received a package from server/Serial.0
2014-11-13 08:09:25,347 [TP-Processor6] INFO  gateway.FrameService  - Received 3 frames from: server/Serial.0
2014-11-13 08:09:25,348 [TP-Processor6] ERROR gateway.FrameService  - FrameParserError: Sender:server/Serial.0 Date:Thu Nov 13 08:09:25 GMT+01:00 2014 Frame:DNVbh6RJAQAAAQAEAQAAaw==
2014-11-13 08:09:25,400 [TP-Processor6] ERROR util.JDBCExceptionReporter  - FEHLER: ungültige Byte-Sequenz für Kodierung »UTF8«: 0x00
2014-11-13 08:09:25,434 [TP-Processor6] ERROR errors.GrailsExceptionResolver  - PSQLException occurred when processing request: [POST] /gateway/frame/saveFlat
FEHLER: ungültige Byte-Sequenz für Kodierung »UTF8«: 0x00. Stacktrace follows:
org.postgresql.util.PSQLException: FEHLER: ungültige Byte-Sequenz für Kodierung »UTF8«: 0x00
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:334)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at gateway.FrameService$FlatHandler.message(FrameService.groovy:105)
	at frame.parser.FrameParser.parse(FrameParser.java:60)
	at frame.parser.FrameParser.parse(FrameParser.java:43)
	at gateway.FrameService.parseFrames(FrameService.groovy:41)
	at gateway.FrameService.saveFlatFrames(FrameService.groovy:72)
	at gateway.FrameController.saveFlat(FrameController.groovy:25)
	at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
	at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
	at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:776)
	at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:705)
	at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:898)
	at java.lang.Thread.run(Thread.java:745)

**Comment by oarchner** [comment]
Checked the import by a test with curl:

Command:
`curl -i -X POST -H 'Content-Type:application/x-www-form-urlencoded' -u admin:xbee http://bayconf.bayceer.uni-bayreuth.de/gateway/frame/saveFlat -d 'sender=TestFrame&bayeosframes[]=DNVbh6RJAQAAAQAEAQAAaw==' `

Response:
`HTTP/1.1 200 OK
Date: Tue, 09 Jun 2015 06:53:59 GMT
Server: Apache/2.2.22 (Debian)
Vary: Accept-Encoding
Content-Length: 13
Content-Type: text/html;charset=utf-8
Frames saved`

Log on Server:
`2015-06-09 08:53:59,288 [TP-Processor3] INFO  gateway.FrameService  - 0/1 frames saved
2015-06-09 08:53:59,288 [TP-Processor3] ERROR gateway.FrameService  - FrameParserError: Sender:TestFrame Date:Tue Jun 09 07:53:59 GMT+01:00 2015 Frame:DNVbh6RJAQAAAQAEAQAAaw==
2015-06-09 08:53:59,287 [TP-Processor3] INFO  gateway.FrameService  - Received 1 frames from: TestFrame
2015-06-09 08:53:59,286 [TP-Processor3] INFO  gateway.FrameController  - Received a package from TestFrame`

No problems. :ok_hand:
